---
title: "Comp_data_10x Young DR samples analysis on Seurat"
author: "Nathalie"
date: "2/8/2021"
output: html_document
---




```{r,include=FALSE, message=FALSE}
library(Seurat)
library(ggplot2)
library(cowplot)
library(patchwork)
library(ggpubr)
library(viridis)
library(ggsci)
```

```{r}
Cell_types= c("Mature adipocyte","Mature adipocyte 2", "Pre-adipocyte (Tshz2)", "Myeloid precursors", "Stem cells", "Pre-adipocyte (Pdea5)", "Endothelial cells", "Muscle cells", "?", "High Mito", "High Dao")
mypal=pal_locuszoom("default",alpha = 0.9)(7)
mypal=c(mypal,"#2E3532","#1b5fb3","#7a2d42","#a67012")
Colours=data.frame(Cell_types,mypal)

```


## Young Samples

### DR young (38)

```{r}
dry_38.data <- Read10X(data.dir = "/Users/njaure/Documents/Main_thesis_project/10X_full_experiment_10.20/comp_data_10.20/38_dry/Solo.out/GeneFull/raw/")
dry_38 <- CreateSeuratObject(counts = dry_38.data, project = "DR", min.cells = 20, min.features = 80)
dry_38
```

* bad quality

### DR young 2 (70)

```{r}
dry2_70.data <- Read10X(data.dir = "/Users/njaure/Documents/Main_thesis_project/10X_full_experiment_10.20/comp_data_10.20/70_dry2/Solo.out/GeneFull/raw/")
dry2_70 <- CreateSeuratObject(counts = dry2_70.data, project = "DR_70", min.cells = 20, min.features = 80)
dry2_70
```


```{r}
dry2_70[["percent.mt"]] <- PercentageFeatureSet(dry2_70, pattern = "^mt-")
plot_vln<-VlnPlot(dry2_70, features = c("nFeature_RNA", "nCount_RNA","percent.mt"), ncol = 3)
plot2 <- FeatureScatter(dry2_70, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot_grid( plot_vln,plot2)
```

```{r, message=FALSE, warning=FALSE}
dry2_70 <- subset(dry2_70, subset = nFeature_RNA > 50 & nFeature_RNA < 200 & nCount_RNA < 1000 & percent.mt < 2)

# store mitochondrial percentage in object meta data
dry2_70 <- PercentageFeatureSet(dry2_70, pattern = "^mt-", col.name = "percent.mt")

# run sctransform
dry2_70 <- SCTransform(dry2_70, vars.to.regress = "percent.mt", verbose = FALSE)


# These are now standard steps in the Seurat workflow for visualization and clustering
dry2_70 <- RunPCA(dry2_70, verbose = FALSE)
dry2_70 <- RunUMAP(dry2_70, dims = 1:30, verbose = FALSE)

dry2_70 <- FindNeighbors(dry2_70, dims = 1:30, verbose = FALSE)
dry2_70 <- FindClusters(dry2_70, verbose = FALSE)
DimPlot(dry2_70, label = TRUE) + NoLegend()
```

* Cluster 3 is made of cells with percentage of ribosomal proteins. Cells that are dead, should be removed from the dataset ? 

### Repartition of counts and feature per cluster 

```{r}
FeaturePlot(dry2_70,features = c("nFeature_RNA", "nCount_RNA"))
```



# Get markers per clusters

```{r fig.height = 12, fig.width = 12}

all.markers_ydr=FindAllMarkers(dry2_70, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25,min.cells.feature = 50)

top_features_ydr=vector()
temp=vector()
for ( i in 0:length(unique(all.markers_ydr$cluster))){
  if (nrow(all.markers_ydr[all.markers_ydr$cluster==i,])>10 ){
     temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:3]
      top_features_ydr<-c(top_features_ydr,temp)
  }else {
    temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:3]
      top_features_ydr<-c(top_features_ydr,temp)
    
  }


}


VlnPlot(dry2_70, features = top_features_ydr, 
    pt.size = 0.2, ncol = 4, stack=TRUE)

```

```{r fig.height = 7, fig.width = 9}

top_features_ydr=vector()
temp=vector()
for ( i in 0:length(unique(all.markers_ydr$cluster))){
  if (nrow(all.markers_ydr[all.markers_ydr$cluster==i,])>10 ){
     temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:6]
      top_features_ydr<-c(top_features_ydr,temp)
  }else {
    temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:nrow(all.markers_ydr[all.markers_ydr$cluster==i,])]
      top_features_ydr<-c(top_features_ydr,temp)
    
  }


}



DoHeatmap(dry2_70,group.by = "ident",features =top_features_ydr  )+ scale_fill_viridis()

```


```{r}
new.cluster.ids <- c("Mature adipocyte","Mature adipocyte 2","Pre-adipocyte (Tshz2)","High mito","High Dao" ,"Pre-adipocyte (Pdea5)","?")

names(new.cluster.ids) <- levels(dry2_70)
dry2_70 <- RenameIdents(dry2_70, new.cluster.ids)

pal=as.vector(Colours[match(levels(dry2_70),Colours$Cell_types),2])
p_dry2_70<-DimPlot(dry2_70, reduction = "umap", label = TRUE, pt.size = 0.5,cols=pal ) + NoLegend()
p_dry2_70

```


#### Remove dead nuclei

```{r}
#Get cell's barcode from the cluster High mito
High_mito=WhichCells(dry2_70, ident = "High mito")

length(colnames(dry2_70)) ## 886

dry2_70_filtered <- CreateSeuratObject(counts = dry2_70.data, project = "DR_70", min.cells = 20, min.features = 80)

dry2_70_filtered <- dry2_70_filtered[,!colnames(dry2_70_filtered) %in% High_mito]

length(colnames(dry2_70_filtered)) ## 809


```


```{r}
dry2_70_filtered[["percent.mt"]] <- PercentageFeatureSet(dry2_70_filtered, pattern = "^mt-")
plot_vln<-VlnPlot(dry2_70_filtered, features = c("nFeature_RNA", "nCount_RNA","percent.mt"), ncol = 3)
plot2 <- FeatureScatter(dry2_70_filtered, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot_grid( plot_vln,plot2)
```

```{r, message=FALSE, warning=FALSE}
dry2_70_filtered <- subset(dry2_70_filtered, subset = nFeature_RNA > 50 & nFeature_RNA < 250 & nCount_RNA < 1000 & percent.mt < 1)

# store mitochondrial percentage in object meta data
dry2_70_filtered <- PercentageFeatureSet(dry2_70_filtered, pattern = "^mt-", col.name = "percent.mt")

# run sctransform
dry2_70_filtered <- SCTransform(dry2_70_filtered, vars.to.regress = "percent.mt", verbose = FALSE)


# These are now standard steps in the Seurat workflow for visualization and clustering
dry2_70_filtered <- RunPCA(dry2_70_filtered, verbose = FALSE)
dry2_70_filtered <- RunUMAP(dry2_70_filtered, dims = 1:30, verbose = FALSE)

dry2_70_filtered <- FindNeighbors(dry2_70_filtered, dims = 1:30, verbose = FALSE)
dry2_70_filtered <- FindClusters(dry2_70_filtered, verbose = FALSE,resolution = 0.8)
DimPlot(dry2_70_filtered, label = TRUE) + NoLegend()
```
### Repartition of counts and feature per cluster 

```{r}
FeaturePlot(dry2_70_filtered,features = c("nFeature_RNA", "nCount_RNA"))
```

```{r}
FeaturePlot(dry2_70_filtered,features = c("Lipe", "Slc1a3", "Atp1a2"))
```

```{r}
FeaturePlot(dry2_70_filtered,features = c("Dao", "Slc7a14", "Fgfr2"))
```


```{r fig.height = 12, fig.width = 12}

all.markers_ydr=FindAllMarkers(dry2_70_filtered, only.pos = TRUE, logfc.threshold = 0.1,min.cells.feature = 30)

top_features_ydr=vector()
temp=vector()
for ( i in 0:length(unique(all.markers_ydr$cluster))){
  if (nrow(all.markers_ydr[all.markers_ydr$cluster==i,])>10 ){
     temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:2]
      top_features_ydr<-c(top_features_ydr,temp)
  }else {
    temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:2]
      top_features_ydr<-c(top_features_ydr,temp)
    
  }


}


VlnPlot(dry2_70_filtered, features = top_features_ydr, 
    pt.size = 0.2, ncol = 4, stack=TRUE)

```

```{r fig.height = 6, fig.width = 6}
FeaturePlot(dry2_70_filtered, features = top_features_ydr, pt.size = 0.2, 
    ncol = 3)
```


```{r fig.height = 7, fig.width = 9}

top_features_ydr=vector()
temp=vector()
for ( i in 0:length(unique(all.markers_ydr$cluster))){
  if (nrow(all.markers_ydr[all.markers_ydr$cluster==i,])>10 ){
     temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:6]
      top_features_ydr<-c(top_features_ydr,temp)
  }else {
    temp= all.markers_ydr[all.markers_ydr$cluster==i,"gene"][1:nrow(all.markers_ydr[all.markers_ydr$cluster==i,])]
      top_features_ydr<-c(top_features_ydr,temp)
    
  }


}



DoHeatmap(dry2_70_filtered,group.by = "ident",features =top_features_ydr  )+ scale_fill_viridis()

```



